config/routes.rb
  Rails.application.routes.draw do
    root to: 'lists#index'
    get "up" => "rails/health#show", as: :rails_health_check
    resources :lists, only: [:index, :show, :new, :create] do
      resources :bookmarks, only:[:new, :create, :destroy]
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmarks = bookmark.all
  end


  def create
    @list = list.find(:params[:id])
  end

  def destroy
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to  lists_path
    else
      render :new
    end
  end
  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_forms.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
<%# you need the brackets because in order to make a new bookmark you need to go through the list page %>
<%= f. input :comment  %>
<%= f. association :movie %>
<%# association since it's an id and not a column %>
<%= f. submit 'submit' %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="">
    <div class="row new-form">
      <div class="col-lg-6 left-bg-list">
      </div>
      <div class="col-lg-6 right-bg" >
        <%= render 'form', bookmark: @bookmark %>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_forms.html.erb
<%= simple_form_for @list do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f. submit 'submit' %>
<% end %>

app/views/lists/index.html.erb
<div class='banner'>
  <h1 class='banner-title'>Watch List</h1>
</div>

<div class='container'>
  <p class="btn-add">
    <%= link_to 'Make a New List', new_list_path, class: 'btn btn-primary' %>
  </p>
</div>

<div class="container">
  <h1>Your Lists</h1>
  <div class="cards-scroll">
    <% @lists.each do |list| %>
      <div class="card">
        <div class="card-content">
          <h2 class="card-title">
            <%= link_to list.name, list_path(list), class: "list-link" %>
          </h2>
          <p class="card-description"></p>
          <%= link_to 'View List', list_path(list), class: 'btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= render 'forms' %>

app/views/lists/show.html.erb
    <div class="movies-grid">
      <% @list.movies.each do |movie| %>
      <div class="box-poster">
        <img class="img-poster" src="<%= movie.poster_url %>">
        <p class="movie-path"><%= movie.title %></p>
      </div>
      <% end %>
    </div>

    <div class='button'>
<%= link_to 'Watch list', lists_path, class:'btn-primary' %>